### ISSUE TITLE
Develop a strategy for SEO/server-side rendering

### ISSUE THREAD

**Issue by aschey** [ClipboardProject/ClipboardApp#39]
Server-side rendering/isomorphic javascript is important in order to maximize search engine optimization. The preferred way to do this seems to be with webpack or some variant + Node, so we need to evaluate if we want to go with a Node + Django hybrid approach or just use Node on the backend.

**Comment by WesThorburn** [comment]
I've thrown together a very rough Nuxt Implementation that offers SSR with minimal config. I thought it'd be best to keep it in a separate repo at first until we're all happy with the direction Nuxt will take us in. [Link to separate repo](https://github.com/ClipboardProject/clipboard-nuxt)

If you're looking through the source code, pages/index.vue is where the meat of the functionality is right now. Currently, it's just using 2 hardcoded dummy event objects, but it's in a state where we can provide it with live data through an API serving JSON.

In a production environment, we'd have Django serving all relevant JSON event data via GET/POST requests. These routes will not be exposed to the public. On the same machine, we'll have the Nuxt app listening for public requests. When a request comes in, Nuxt will access the relevant API locally, generate the HTML page containing the page's event data and return the response to the user.

The nuxt process will need to be daemonized in production. I recommend using PM2 for this. One downside is that when pushing client-side changes, the app has to be rebuilt and the nuxt process needs to be restarted, nothing too serious, just an extra step.
